name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-patch

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: diffusers
      notebook_folder: diffusers_doc
      languages: en ko
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
